name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: AzureCount
      run: az login --scope https://management.azure.com/.default
    - name: Azure
      run: az account set --subscription 86a0602e-90f9-498d-8821-5249a6d7effa
    - name: AzureWork
      run: az configure --defaults workspace=mlops-work-group group=mlops-group
    - name: Aprovisionar train compute
      run: az ml compute create -n train-machine --type amlcompute --min-instances 0 --max-instances 4
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml

