name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Aprovisionar train compute
      run: az ml compute create -n cpu-cluster --type amlcompute --min-instances 0 --max-instances 4


