name: Code checks simulator

on:
  workflow_dispatch:

jobs:
  mostrar:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
            echo "Will add code checks here in next challenge"
